// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cSwBPf7XwoGVIvx08Xc5-oYygFQk-ys',
    appId: '1:781101989979:web:1eac8bcb76dd39465a3f7e',
    messagingSenderId: '781101989979',
    projectId: 'gamerxhub-99fce',
    authDomain: 'gamerxhub-99fce.firebaseapp.com',
    storageBucket: 'gamerxhub-99fce.appspot.com',
    measurementId: 'G-J4J92M0BFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWyMSVVL_P4IhN__b9pem9XaTq51EqDWc',
    appId: '1:781101989979:android:bd3e4878a74c9ed05a3f7e',
    messagingSenderId: '781101989979',
    projectId: 'gamerxhub-99fce',
    storageBucket: 'gamerxhub-99fce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9VGN6wJerz6KVXq4dAmdJH_Baqkg_IDw',
    appId: '1:781101989979:ios:796cbec35e3161b55a3f7e',
    messagingSenderId: '781101989979',
    projectId: 'gamerxhub-99fce',
    storageBucket: 'gamerxhub-99fce.appspot.com',
    iosBundleId: 'com.gamerx.gamerxhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9VGN6wJerz6KVXq4dAmdJH_Baqkg_IDw',
    appId: '1:781101989979:ios:bc58148cd2348e2b5a3f7e',
    messagingSenderId: '781101989979',
    projectId: 'gamerxhub-99fce',
    storageBucket: 'gamerxhub-99fce.appspot.com',
    iosBundleId: 'com.gamerx.gamerxhub.RunnerTests',
  );
}
